[project]
name = "masterchef-rag-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "contractions>=0.1.73",
    "faiss-cpu>=1.13.2",
    "fastapi>=0.135.1",
    "flashrank>=0.2.10",
    "langchain>=1.2.13",
    "langchain-classic>=1.0.3",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.20",
    "langchain-experimental>=0.4.1",
    "langchain-text-splitters>=1.1.1",
    "nltk>=3.9.3",
    "pypdf>=6.9.1",
    "python-telegram-bot>=22.7",
    "ragas>=0.4.3",
    "requests>=2.32.5",
    "sentence-transformers>=5.3.0",
    "sqlite-vec>=0.1.7",
    "uvicorn>=0.42.0",
]
